USE [master]
GO

-- Crear la nueva base de datos
CREATE DATABASE [DB_RECOLECCION_RECICLAJE]
GO

USE [DB_RECOLECCION_RECICLAJE]
GO

-- Crear el esquema para la organización
CREATE SCHEMA [SCH_RECIQUEST]
GO

-- Tabla de Roles
CREATE TABLE [SCH_RECIQUEST].[T_ROLES]
(
	[ROL_ID] INT IDENTITY(1,1) NOT NULL,
	[NOMBRE] VARCHAR(50) NOT NULL,
	[PERMISO] VARCHAR(MAX) NOT NULL,
	[ESTADO] BIT NOT NULL DEFAULT(1)

	CONSTRAINT [PK_T_ROLE_USUARIO] PRIMARY KEY CLUSTERED
	(
		[ROL_ID] ASC
	)
)
GO

-- Tabla para Usuarios
CREATE TABLE [SCH_RECIQUEST].[T_USUARIOS]
(
    [USUARIO_ID] INT IDENTITY(1,1) NOT NULL,
    [NOMBRE] VARCHAR(50) NOT NULL,
    [APELLIDO] VARCHAR(50) NOT NULL,
    [INDENTIFICACION] VARCHAR(150) NOT NULL,
    [NUM_TELEFONO] VARCHAR(15) NOT NULL,
    [CORREO_ELECTRONICO] VARCHAR(100) NOT NULL,
	[CONTRASENA] VARCHAR (100) NOT NULL,
    [ROL_ID] INT NOT NULL

	CONSTRAINT [PK_T_USUARIOS] PRIMARY KEY CLUSTERED
	(
		[USUARIO_ID] ASC
	)
)
GO
CREATE TABLE [SCH_RECIQUEST].[T_FECHA]
(
 [FECHA_ID] INT IDENTITY(1,1) NOT NULL,
 [FECHA] VARCHAR(30) NOT NULL,
 CONSTRAINT [PK_FECHA] PRIMARY KEY CLUSTERED
	(
		[FECHA_ID] ASC
	)
)
GO

CREATE TABLE [SCH_RECIQUEST].[T_HORA]
(
 [HORA_ID] INT IDENTITY(1,1) NOT NULL,
 [HORA] VARCHAR(30) NOT NULL,
 CONSTRAINT [PK__HORA] PRIMARY KEY CLUSTERED
	(
		[HORA_ID] ASC
	)
)
GO 
CREATE TABLE [SCH_RECIQUEST].[T_PROVINCIA]
(
 [PROVINCIA_ID] INT IDENTITY(1,1) NOT NULL,
 [PROVINCIA] VARCHAR(50) NOT NULL
 CONSTRAINT [PK__PROVINCIA] PRIMARY KEY CLUSTERED
	(
		[PROVINCIA_ID] ASC
	)
)
GO


-- Tabla para Peticiones de Recolección
CREATE TABLE [SCH_RECIQUEST].[T_PROGRAMAR_RECOLECCION]
(
    [PETICION_ID] INT IDENTITY(1,1) NOT NULL,
	[DETALLES_EDIFICIO] VARCHAR(250) NOT NULL,
    [CODIGO_POSTAL] INT NOT NULL,
    [MUNICIPIO] VARCHAR(50) NOT NULL,
    [PROVINCIA] INT NOT NULL, -- FORANEA
	[CANTON] VARCHAR(50) NOT NULL,
	[FECHA] INT NOT NULL, --FORANEA
	[HORA] INT NOT NULL,  --FORANEA
	--[ROL_ID] INT NOT NULL, --- hay que corregir aqui -- Son usuarios
	[USUARIO_ID] INT NOT NULL, 

	CONSTRAINT [PK__PROGRAMAR_RECOLECCION] PRIMARY KEY CLUSTERED
	(
		[PETICION_ID] ASC
	)
)
GO

CREATE TABLE [SCH_RECIQUEST].[T_NOMBRE_MATERIAL]
(
 [NOMBRE_MATERIAL_ID] INT IDENTITY(1,1) NOT NULL,
 [NOMBRE] VARCHAR(50) NOT NULL
 CONSTRAINT [PK__NOMBRE_MATERIAL] PRIMARY KEY CLUSTERED
	(
		[NOMBRE_MATERIAL_ID] ASC
	)
)
GO

CREATE TABLE [SCH_RECIQUEST].[T_MATERIALES]
(
	[MATERIAL_ID] INT IDENTITY(1,1)NOT NULL,
	[NOMBRE_MATERIAL_ID] INT NOT NULL, --FORANEA
	--[PESO] INT NOT NULL, --Quitar este Default -- Es un varchar de 8 datos
	[PESO] VARCHAR(8) NOT NULL,
	[PETICION_ID] INT NOT NULL,

	CONSTRAINT [PK_T_MATERIALES] PRIMARY KEY CLUSTERED
	(
		[MATERIAL_ID] ASC
	)
)
GO

--FK's--
ALTER TABLE [SCH_RECIQUEST].[T_MATERIALES]
ADD CONSTRAINT [FK_MATERIALES_PETICION_ID] FOREIGN KEY (PETICION_ID)
REFERENCES [SCH_RECIQUEST].[T_PROGRAMAR_RECOLECCION] 
GO
ALTER TABLE [SCH_RECIQUEST].[T_MATERIALES]
CHECK CONSTRAINT [FK_MATERIALES_PETICION_ID]
GO

ALTER TABLE [SCH_RECIQUEST].[T_USUARIOS]
ADD CONSTRAINT [FK_USUARIOS_ROL_ID] FOREIGN KEY (ROL_ID)
REFERENCES [SCH_RECIQUEST].[T_ROLES] 
GO
ALTER TABLE [SCH_RECIQUEST].[T_USUARIOS]
CHECK CONSTRAINT [FK_USUARIOS_ROL_ID]
GO

--ALTER TABLE [SCH_RECIQUEST].[T_PROGRAMAR_RECOLECCION]
--ADD CONSTRAINT [FK_PROGRAMAR_RECOLECCION_ROL_ID] FOREIGN KEY (ROL_ID)
--REFERENCES [SCH_RECIQUEST].[T_ROLES] 
--GO
--ALTER TABLE [SCH_RECIQUEST].[T_PROGRAMAR_RECOLECCION]
--CHECK CONSTRAINT [FK_PROGRAMAR_RECOLECCION_ROL_ID]
--GO
ALTER TABLE [SCH_RECIQUEST].[T_PROGRAMAR_RECOLECCION]
ADD CONSTRAINT [FK_PROGRAMAR_RECOLECCION_USUARIO_ID] FOREIGN KEY (USUARIO_ID)
REFERENCES [SCH_RECIQUEST].[T_USUARIOS] 
GO
ALTER TABLE [SCH_RECIQUEST].[T_PROGRAMAR_RECOLECCION]
CHECK CONSTRAINT [FK_PROGRAMAR_RECOLECCION_USUARIO_ID]
GO

ALTER TABLE [SCH_RECIQUEST].[T_PROGRAMAR_RECOLECCION]
ADD CONSTRAINT [FK_PROGRAMAR_RECOLECCION_FECHA] FOREIGN KEY ([FECHA])
REFERENCES [SCH_RECIQUEST].[T_FECHA]([FECHA_ID])
GO

ALTER TABLE [SCH_RECIQUEST].[T_PROGRAMAR_RECOLECCION]
CHECK CONSTRAINT [FK_PROGRAMAR_RECOLECCION_FECHA]
GO

ALTER TABLE [SCH_RECIQUEST].[T_PROGRAMAR_RECOLECCION]
ADD CONSTRAINT [FK_PROGRAMAR_RECOLECCION_HORA] FOREIGN KEY ([HORA])
REFERENCES [SCH_RECIQUEST].[T_HORA]([HORA_ID])
GO

ALTER TABLE [SCH_RECIQUEST].[T_PROGRAMAR_RECOLECCION]
CHECK CONSTRAINT [FK_PROGRAMAR_RECOLECCION_HORA]
GO

ALTER TABLE [SCH_RECIQUEST].[T_PROGRAMAR_RECOLECCION]
ADD CONSTRAINT [FK_PROGRAMAR_RECOLECCION_PROVINCIA] FOREIGN KEY ([PROVINCIA])
REFERENCES [SCH_RECIQUEST].[T_PROVINCIA]([PROVINCIA_ID])
GO

ALTER TABLE [SCH_RECIQUEST].[T_PROGRAMAR_RECOLECCION]
CHECK CONSTRAINT [FK_PROGRAMAR_RECOLECCION_PROVINCIA]
GO

ALTER TABLE [SCH_RECIQUEST].[T_MATERIALES]
ADD CONSTRAINT [FK_MATERIALES_NOMBRE_MATERIAL] FOREIGN KEY ([NOMBRE_MATERIAL_ID])
REFERENCES [SCH_RECIQUEST].[T_NOMBRE_MATERIAL]([NOMBRE_MATERIAL_ID])
GO
ALTER TABLE [SCH_RECIQUEST].[T_MATERIALES]
CHECK CONSTRAINT [FK_MATERIALES_NOMBRE_MATERIAL]
GO

--Insert Roles
INSERT INTO [SCH_RECIQUEST].[T_ROLES] ([NOMBRE], [PERMISO], [ESTADO])
VALUES
('ADMINISTRADOR','{"PermisoCategoriaAdministrador":{"Guardar":true,"Editar":true,"Acceso":true,"Eliminar":true}',1),
('USUARIOS','{PermisoCategoriaUsuarioL{"Guardar:True"}}',1)
GO

--Insert Usuarios
INSERT INTO [SCH_RECIQUEST].[T_USUARIOS] ([NOMBRE], [APELLIDO], [INDENTIFICACION], [NUM_TELEFONO], [CORREO_ELECTRONICO], [CONTRASENA], [ROL_ID])
VALUES
    ('Michael', 'Marin Mora', '118930423', 'numTelefono', 'mikevip@gmail.com', 'malito123', 1),
    ('Jean', 'Mendoza', '12345676543', 'numTelefono', 'JeanVips@gmail.com', 'malito123', 2)
GO

--Insert Fechas
INSERT INTO [SCH_RECIQUEST].[T_FECHA] ([FECHA]) 
VALUES
('SABADO'),
('DOMINGO'),
('LUNES'),
('MARTES'),
('MIERCOLES'),
('JUEVES'),
('VIERNES')
GO

--Insert Hora
INSERT INTO [SCH_RECIQUEST].[T_HORA] ([HORA]) 
VALUES
('12:00:00'),
('15:00:00')
GO

--Insert Provincia
INSERT INTO [SCH_RECIQUEST].[T_PROVINCIA] ([PROVINCIA])
VALUES
    ('San José'),
    ('Alajuela'),
    ('Cartago '),
	('Heredia'),
    ('Puntarenas'),
	('Guanacaste'),
    ('Limón')
GO
------------------------------- En ves de roles va Usuarios -------------------------------------------------

--Insert Recoleccion
INSERT INTO [SCH_RECIQUEST].[T_PROGRAMAR_RECOLECCION] ([DETALLES_EDIFICIO],[CODIGO_POSTAL],[MUNICIPIO],[PROVINCIA],[CANTON],[FECHA],[HORA],[USUARIO_ID])
VALUES
    ('Detalles Edificio 1', 12345, 'Municipio1', 1, 'Canton1', 1, 1, 1),
    ('Detalles Edificio 2', 67890, 'Municipio2', 2, 'Canton2', 2, 2, 2)
    --(3, 'Detalles Edificio 3', 98765, 'Municipio3', 3, 'Canton3', 3, 3, 3)
GO

--Insert Nombre Materiales
INSERT INTO [SCH_RECIQUEST].[T_NOMBRE_MATERIAL] ([NOMBRE])
VALUES
    ('Papel y cartón'),
    ('Vidrio'),
    ('Plástico'),
    ('Metal'),
    ('Tetabrick'),
    ('Corcho'),
	('Madera'),
    ('No reciclables')
GO
 ---------------------------------Se cambiar el peso (int) a Un varchar el cual seria 1kg a 1000kg, varchar de 8 datos-------------------------------------------

--Insert Materiales
INSERT INTO [SCH_RECIQUEST].[T_MATERIALES] (NOMBRE_MATERIAL_ID, PESO, PETICION_ID)
VALUES
   (1, 1000, 1)
GO

